### ISSUE TITLE
Pod does not compile with CocoaPods 1.6.0

### ISSUE THREAD

**Issue by bpollock-vida** [Appboy/appboy-ios-sdk#176]
* [ x ] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.1
 SDK Version             | 3.12.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.1
 Repro rate              | all the time (100%)
 
## What did you do?
Install Appboy via cocoa pods after upgrading from 1.5.3 to 1.6.0 cocoa pods

## What did you expect to happen?
App to build normally

## What happened instead?

I get the following error after building the app and trying to compile:

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CTTelephonyNetworkInfo", referenced from:
      objc-class-ref in libAppboyKitLibrary.a(ABKDevice.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Upgrading from appboy version 3.8.3 to 3.12.0 did not fix the issue.
App WILL build if I remove appboy from podfile and code.

We also have some 20% time reproducible failures in travis with:
"Multiple commands produce SDWebImage" which may be related to your pod configuration as well since it seems to be a dependency of app boy?

## Steps to reproduce

* Add app boy
* pod install
* Build app
* App fails to build with error

## Code Snippet

source 'https://github.com/CocoaPods/Specs.git'
workspace "Vida"
project 'Vida.xcodeproj'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks!
platform :ios, '9.0'

target 'Vida' do
  pod 'Appboy-iOS-SDK', '= 3.12.0'
...
end

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

Nope

## Project that demonstrates the issue

attached in email. too big here

**Comment by Bucimis** [comment]
Hi @bpollock-vida, we're currently investigating adding Cocoapods 1.6.0 support and will have more information on timelines when available.

**Comment by kleiberjp** [comment]
I am having the same issue

**Comment by Bucimis** [comment]
@bpollock-vida @kleiberjp We’re affected by the bug posted here https://github.com/CocoaPods/CocoaPods/issues/8493 Cocoapods is planning to fix the bug in `1.6.1`. In the meantime, we recommend continuing to use Cocoapods `1.5.3`.

**Comment by geoffmacd** [comment]
plus one to this issue

**Comment by Bucimis** [comment]
Hi @geoffmacd @bpollock-vida, Cocoapods 1.6.1 was released and should work with our SDK. Thanks & feel free to refile if 1.6.1 doesn't work for you

**Comment by shauket** [comment]
the issue still persists. 
XCode 10.1

# Uncomment the next line to define a global platform for your project


target 'BrazePushNotification' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
 platform :ios, '9.0'

  # Pods for BrazePushNotification
  pod 'Appboy-iOS-SDK', '= 3.12.0'

end
