### ISSUE TITLE
Swift example doesn't compile with Xcode 6.4

### ISSUE THREAD

**Issue by Clifton-Roberts** [Appboy/appboy-ios-sdk#26]
Hi there,

I'm unable to compile your ```HelloSwift``` example project on Xcode 6.4. 

We're trying to integrate your SDK into our app with a Podfile similar to the one in the ```HelloSwift``` example, so if you have any ideas on how to make this work, I'd very much appreciate the insight!

Output:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Appboy", referenced from:
      __TMaCSo6Appboy in ViewController.o
      __TMaCSo6Appboy in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Wenzhi** [comment]
Hi @Clifton-Roberts, may I ask which cocoapods version you are using for the `pod install` and `pod update`?

**Comment by Clifton-Roberts** [comment]
Hey, @Wenzhi, I'm using version ```0.38.0```.

**Comment by Wenzhi** [comment]
@Clifton-Roberts It seems that Cocoapods `0.38.0` change the way of building a dynamic framework from a static library. I'm still looking at it and trying to find a way to workaround.
Are you using `use_frameworks!` in your Podfile? If you don't, directly use the static library should work.

**Comment by Clifton-Roberts** [comment]
@Wenzhi We do have ```use_frameworks!``` in our Podfile. Unfortunately, I don't see a way to disable this on an individual basis.

**Comment by Clifton-Roberts** [comment]
Could this be the reason for the issue? https://github.com/CocoaPods/CocoaPods/pull/3859/

**Comment by Wenzhi** [comment]
Thank you for helping the investigation! I saw the [issue](https://github.com/CocoaPods/CocoaPods/issues/3857) too, but I'm not really sure if it's going to fix the problem.

The issue `Undefined symbols` usually is a linker issue or a library/framework search path issue. From the xcconfig files Cocoapods generated, they are all pointing to the Appboy_iOS_SDK.framework in the build folder. However, in Cocoapods `0.37.2`, the file `Appboy_iOS_SDK.framework/Appboy_iOS_SDK` was 1.3MB, while in `0.38.0`, the file is only 12KB, which makes me think the library might not be bundled in the framework properly.

I'm going to file an issue on the Cocoapods repo. I think for now, you can either downgrade your Cocoapods back to 0.37.2 to make it work, or use the manual integration. Usually the Cocoapods community respond fast; we'll also look into Cocoapods source to see if we can track down the issue.

**Comment by perotinus** [comment]
Yes, the referenced PR almost certainly won't fix this issue. It only affects header search paths, and since everything is compiling fine, that's not the issue here.

**Comment by perotinus** [comment]
Potentially relevant: https://github.com/CocoaPods/CocoaPods/issues/3773

**Comment by Wenzhi** [comment]
Thank you @perotinus ! I filed a new issue https://github.com/CocoaPods/CocoaPods/issues/3870 mentioning it.

**Comment by jkopelioff** [comment]
Here is the fix...

We're able to fix this locally with this in our Podfile:

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "Appboy-iOS-SDK"
        config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
      end
    end
  end
end

**Comment by Wenzhi** [comment]
Thank you so much @jkopelioff ! I'll also test it and then update our documentation and our sample code.
